// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBBlTJvLwxy1yexF35OvFYUqytlGJYxYY',
    appId: '1:16635881131:web:48c6ab7369fef5851cb9ee',
    messagingSenderId: '16635881131',
    projectId: 'shopit-c260e',
    authDomain: 'shopit-c260e.firebaseapp.com',
    storageBucket: 'shopit-c260e.firebasestorage.app',
    measurementId: 'G-KK8362REGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-09zZeBg-uAEWq4UUZrNUcYubZf7Genw',
    appId: '1:16635881131:android:dea5b5bbc5b816891cb9ee',
    messagingSenderId: '16635881131',
    projectId: 'shopit-c260e',
    storageBucket: 'shopit-c260e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYPQ4753Uo0h2AHRUrUrRJii8mIWSj9RY',
    appId: '1:16635881131:ios:5b21825d3e2b53571cb9ee',
    messagingSenderId: '16635881131',
    projectId: 'shopit-c260e',
    storageBucket: 'shopit-c260e.firebasestorage.app',
    iosBundleId: 'com.example.shopit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYPQ4753Uo0h2AHRUrUrRJii8mIWSj9RY',
    appId: '1:16635881131:ios:5b21825d3e2b53571cb9ee',
    messagingSenderId: '16635881131',
    projectId: 'shopit-c260e',
    storageBucket: 'shopit-c260e.firebasestorage.app',
    iosBundleId: 'com.example.shopit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBBlTJvLwxy1yexF35OvFYUqytlGJYxYY',
    appId: '1:16635881131:web:7328fca09724b2501cb9ee',
    messagingSenderId: '16635881131',
    projectId: 'shopit-c260e',
    authDomain: 'shopit-c260e.firebaseapp.com',
    storageBucket: 'shopit-c260e.firebasestorage.app',
    measurementId: 'G-4FC1ZCEJZX',
  );
}
